### ISSUE TITLE
Improvement/Bug – Build/Publish arm64 binaries and images

### ISSUE THREAD

**Issue by lbarnkow** [bakito/sealed-secrets-web#32]
Please consider adding arm64 as target architecture to your CI/CD pipeline.

**Comment by bakito** [comment]
@lbarnkow could you please also check the binary `/usr/local/bin/kubeseal` if this also is amd64 formatted.
I currently to not have the possibility to verify arm64

**Comment by bakito** [comment]
@lbarnkow I split the build config into separate amd/arm builds, images are being pushed under tag `main`.
Could you please verify if the 3 binaries dumb-init, sealed-secrets-web and kubeseal are correct now?

**Comment by lbarnkow** [comment]
I pulled `ghcr.io/bakito/sealed-secrets-web:main` both on amd64 and arm64 machines.

There is no amd64-image anymore available at tag `:main`. Don't know if you were aware.

On arm64 everything is fine now: :+1: 

```sh
$ podman  pull ghcr.io/bakito/sealed-secrets-web:main
Trying to pull ghcr.io/bakito/sealed-secrets-web:main...
Getting image source signatures
Copying blob 11c1139baea4 done  
Copying blob 1a34f183c49c done  
Copying blob 9b3977197b4f done  
Copying blob 0d22d12edcc0 done  
Copying blob 4dacc96e0b4d done  
Copying config 8a8930a769 done  
Writing manifest to image destination
Storing signatures
8a8930a7698a9901738d73ed8d69469592b173c66f11505f47e84c2185d83219

$ podman inspect ghcr.io/bakito/sealed-secrets-web:main | grep Arch
        "Architecture": "arm64",

$ podman run --rm -d --entrypoint /bin/sh ghcr.io/bakito/sealed-secrets-web:main -c 'sleep 600'
38dd00a4c3acf2d351d2e81cfc0e2f9b9926d2be6a6bbd6adcd4cd2a8aa19d37

$ podman cp 38:/usr/local/bin/kubeseal .
$ podman cp 38:/usr/bin/dumb-init .
$ podman cp 38:/opt/go/sealed-secrets-web .

$ file dumb-init 
dumb-init: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, stripped

$ file kubeseal 
kubeseal: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, no section header

$ file sealed-secrets-web 
sealed-secrets-web: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, no section header
```

**Comment by bakito** [comment]
😲 no I was not ware of this!! 
Thank you very much for mentioning this.

I could fix it, there are again 2 versions and also the arch of sealed-secrets-web and kubeseal is automatically checked during the build.

Could you please verify it yourself with the latest main tag?

**Comment by lbarnkow** [comment]
Both images look good to me. :tada: 

### arm64 :+1: 

```sh
$ podman pull ghcr.io/bakito/sealed-secrets-web:main
Trying to pull ghcr.io/bakito/sealed-secrets-web:main...
Getting image source signatures
Copying blob 9b3977197b4f done  
Copying blob c08dd47a5ca8 done  
Copying blob d84855a25753 done  
Copying blob 3b7698224f64 done  
Copying blob 382f1d341db6 done  
Copying config a6b0faa0f2 done  
Writing manifest to image destination
Storing signatures

$ podman inspect ghcr.io/bakito/sealed-secrets-web:main | grep Arch
        "Architecture": "arm64",

$ podman run --rm -d --entrypoint /bin/sh ghcr.io/bakito/sealed-secrets-web:main -c 'sleep 600'
9c2ca4c412868125915da230127dc4231fc14609c7f53266f8eb2995a354334b

$ podman cp 9c:/usr/local/bin/kubeseal .                                                       
$ podman cp 9c:/usr/bin/dumb-init .     
$ podman cp 9c:/opt/go/sealed-secrets-web .

$ file dumb-init 
dumb-init: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, stripped

$ file kubeseal 
kubeseal: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, no section header

$ file sealed-secrets-web 
sealed-secrets-web: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, no section header
```

### amd64 :+1: 

```sh
$ docker pull ghcr.io/bakito/sealed-secrets-web:main
main: Pulling from bakito/sealed-secrets-web
59bf1c3509f3: Already exists 
c08dd47a5ca8: Pull complete 
e763a41b9068: Pull complete 
e3f590a4144d: Pull complete 
f985368c3d35: Pull complete 
Digest: sha256:7aef59e6778bce5d795948d2a4dc73f502be72244900ac8288f42229e2f74853
Status: Downloaded newer image for ghcr.io/bakito/sealed-secrets-web:main
ghcr.io/bakito/sealed-secrets-web:main

$ docker inspect ghcr.io/bakito/sealed-secrets-web:main | grep Arch
        "Architecture": "amd64",

$ docker run --rm -d --entrypoint /bin/sh ghcr.io/bakito/sealed-secrets-web:main -c 'sleep 600'
3e4669378f368f8c58ef1c3b9b35975176a8c15d776e3c893a96dbf98d247a54

$ docker cp 3e:/usr/local/bin/kubeseal .
$ docker cp 3e:/usr/bin/dumb-init .
$ docker cp 3e:/opt/go/sealed-secrets-web .

$ file dumb-init 
dumb-init: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped

$ file kubeseal 
kubeseal: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, no section header

$ file sealed-secrets-web 
sealed-secrets-web: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, no section header
```

**Comment by lbarnkow** [comment]
Thank you very much for the quick work on this! :heart:

**Comment by bakito** [comment]
fixed in https://github.com/bakito/sealed-secrets-web/releases/tag/v2.7.1

**Comment by purduemike** [comment]
I'm still seeing this error in ghcr.io/bakito/sealed-secrets-web:v3.1.0.

`[dumb-init] /opt/go/sealed-secrets-web: Exec format error`

Is there some flag you need to set to use arm64?

**Comment by purduemike** [comment]
AFAICT this broke in 3.0.0. The last working version for arm64 is 2.8.3.

Could you fix?

**Comment by bakito** [comment]
@purduemike can please try with the latest main tag image? 
https://github.com/bakito/sealed-secrets-web/pkgs/container/sealed-secrets-web/97476935?tag=main

**Comment by purduemike** [comment]
Yes, main works perfectly!

**Comment by bakito** [comment]
Please check https://github.com/bakito/sealed-secrets-web/releases/tag/v3.1.1

**Comment by purduemike** [comment]
@bakito Thank you for the quick turn around!
